function s2 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  S2 = IMPORTFILE(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  S2 = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  S2 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  s2 = importfile("C:\Users\mjuntune\Documents\Publications\PCD-CTA\1-s2.0-S1934592524004611-mmc1.xlsx", "Sheet1", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Mar-2025 14:17:58

%% Input handling

% If no sheet is specified, read from Sheet1
if nargin == 1 || isempty(sheetName)
    sheetName = "Sheet1";
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [3, inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "ForceCADRADS", "AlphaCADRADS", "QCACADRADS"];
opts.SelectedVariableNames = ["ForceCADRADS", "AlphaCADRADS", "QCACADRADS"];
opts.VariableTypes = ["char", "char", "char", "char", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4"], "EmptyFieldRule", "auto");

% Import the data
s2 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    s2 = [s2; tb]; %#ok<AGROW>
end

end